spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: info
    com.gongdi.materialpoints: info
